export const SITE = {
  name: "502 Junk Dept.",
  legalName: "502 Junk Department",
  ownerFirstName: "Hunter",
  ownerFullName: "Hunter Rowe",
  tagline: "We Want Louisville's Junk",
  shortPitch: "Fast, local, same-day junk removal and demolition serving Louisville, KY and Southern Indiana.",
  phone: "(502) 501-9299",
  phoneRaw: "+15025019299",
  phoneHref: "tel:+15025019299",
  smsHref: "sms:+15025019299",
  email: "quotes@502junk.com",
  hours: {
    display: "Open 7 days a week",
    json: [
      { dayOfWeek: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"], opens: "07:00", closes: "20:00" },
    ],
  },
  city: "Louisville",
  region: "KY",
  metro: "Louisville Metro & Southern Indiana",
  serviceAreaName: "Louisville & Kentuckiana",
  zip: "40202",
  geo: { lat: 38.2527, lng: -85.7585 },
  founder: "Hunter Rowe",
  reviews: {
    count: 115,
    rating: 5.0,
    source: "Google",
    writeReviewUrl: "https://search.google.com/local/writereview?placeid=ChIJ40OSJqVMwoURf55aXrKZHIE",
  },
  socials: {
    facebook: "https://www.facebook.com/502junk/",
    instagram: "https://www.instagram.com/502junk/",
    googleBusiness: "https://search.google.com/local/reviews?placeid=ChIJ40OSJqVMwoURf55aXrKZHIE",
  },
  url: "https://www.502junk.com",
  vercelUrl: "https://502junk.vercel.app",
};

export const PRICING_TIERS = [
  { name: "Minimum Load", price: 125, blurb: "A single bulky item, a couple of pieces, or a small pile cleared in one stop." },
  { name: "1/4 Load",     price: 225, blurb: "Perfect for a handful of large items or a small-to-medium pile of clutter." },
  { name: "1/2 Load",     price: 350, blurb: "Medium-sized cleanouts that don't need a full trailer." },
  { name: "3/4 Load",     price: 475, blurb: "Multiple bulky items — couches, furniture, construction debris." },
  { name: "Full Load",    price: 650, blurb: "Major hauls — garages, basements, a serious clutter problem solved." },
  { name: "XL Load",      price: 975, blurb: "Property cleanouts, estate cleanouts, and extreme space-reclaim jobs." },
];

export const INCLUDED_IN_EVERY_JOB = [
  "Free, no-obligation estimate",
  "Two-person crew & labor",
  "Truck, fuel, and transport",
  "Recycling, donation, and proper disposal",
  "Full cleanup after the haul",
];

export const ITEMS_WE_TAKE = [
  "Couches & sectionals",
  "Recliners & loveseats",
  "Mattresses & box springs",
  "Dressers & armoires",
  "Dining tables & chairs",
  "Office furniture & desks",
  "Refrigerators & freezers",
  "Washers & dryers",
  "Stoves & ovens",
  "Dishwashers",
  "Water heaters",
  "Microwaves",
  "TVs & monitors",
  "Computers & printers",
  "Stereos & speakers",
  "Treadmills & exercise equipment",
  "Hot tubs & spas",
  "Pianos & organs",
  "Pool tables",
  "BBQ grills",
  "Patio furniture",
  "Lawn mowers & yard equipment",
  "Bicycles",
  "Toys & playsets",
  "Cardboard & moving boxes",
  "Construction debris",
  "Drywall & lumber",
  "Carpet & padding",
  "Tile & flooring",
  "Yard waste & brush",
  "Tree limbs (cut)",
  "Sheds & playhouses",
  "Decks & fencing",
  "Above-ground pools",
  "Tires (limited quantity)",
  "General household clutter",
];

export const ITEMS_WE_DONT_TAKE = [
  "Hazardous chemicals or solvents",
  "Wet or unsealed paint",
  "Asbestos",
  "Medical or biohazard waste",
  "Live ammunition or explosives",
];
